# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        auto_rotate_with_resizing:
            filters:
                auto_rotate: ~
                relative_resize: { widen: 120 }
        downscale_to_1200x1200:
            filters:
                downscale:
                    max: [1200, 1200]

        downscale_to_300x300:
            filters:
                downscale:
                    max: [300, 300]

        upscale_to_300x300:
            filters:
                upscale:
                    min: [300, 300]

        upscale_to_600x600:
            filters:
                upscale:
                    min: [600, 600]

        watermark_image:
            filters:
                watermark:
                    image: ../public/images/watermark.png
                    size: 1
                    position: center
                thumbnail:
                    size: [320, 240]
