index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template:  'index.html.twig'

auto_rotate:
    path: /auto_rotate
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template:  'auto_rotate.html.twig'

downscale_upscale:
    path: /downscale_upscale
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template:  'downscale_upscale.html.twig'
